export const TRANSLATETEXT = {
  Title: 'Typescript Demo',
  UseState: 'useState Example',
  UseEffect: 'useEffect Example',
  UseContext: 'useContext Example',
  UseRef: 'useRef Example',
  UseReducer: 'useReducer Example',
  UseCallback: 'useCallback & useMemo Example',
  CustomHook: 'CustomHook Example',
  Red: 'Red',
  White: 'White',
  Green: 'Green',
  Count: 'Count: ',
  Calculation: 'Calculation: ',
  Current: 'Current Value: ',
  Previous: 'Previous Value: ',
  Welcome: 'Welcome, ',
  Increase: 'Increase',
  AddTodo: 'Add Todo',
  MyTodos: 'My Todos',
  ExpensiveCalculation: 'Expensive Calculation',
};
