export const RoutesName = {
  HOMESCREEN: 'HOMESCREEN',
  USESTATE: 'USESTATE',
  USEEFFECT: 'USEEFFECT',
  USECONTEXT: 'USECONTEXT',
  USEREF: 'USEREF',
  USEREDUCER: 'USEREDUCER',
  USECALLBACKMEMO: 'USECALLBACKMEMO',
  CUSTOM: 'CUSTOM',
};
